### ISSUE TITLE
Homework 1 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw1-jothish21#1]
Dear [Jothish21] -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

Overall good job. You just need to take a second look at your plots and how someone might view them if they weren't in the class. Also, if it helps, markdown allows you to include text outside of the code chunks. This could be used for your discussoin/narrative questions.

---

### Exercise 1: `[10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: [Good Job]

### Exercise 2: `[20/ 20 points]`

a. `[8 / 8 points]`

  - Histogram: `[3 / 3]`
  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: [It might be a good idea to label you x axis so that viewers (unfamiliar with the topic) can understand it at first glance.]

b. `[5 / 5 points]`

  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: [Insert feedback here.]

c. `[2 / 2 points]`

  - Feedback: [You removed the actual years and not the x-axis title. Just having "year" there tells the viewer nothing. The graph also added redundancy with the men and women labels AND the legend.]
- [x] Resolved

d. `[5 / 5 points]`

  - Time series plot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: [Confidence intervals might have been a better choice here than a regresison line.]

### Exercise 3: `[20 / 20 points]`

a. `[2 / 2]`
  - Feedback: [Insert feedback here.]

b. `[2 / 2]`
  - Feedback: [Insert feedback here.]

c. `[16 / 16]` (2 points each)
  - Feedback: [Here you might want to use the grid.arrange(), to align the graphs. Some info: https://cran.r-project.org/web/packages/gridExtra/vignettes/arrangeGrob.html]

- [x] Resolved
  
### Exercise 4: `[10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: [The x-axis doesn't make sense as it doesn't show each neighborhood pricing over time, but instead shows pricing for a random year.]

- [x] Resolved
Additional feedback: the x-axis labels are unreadable. If you want to use this type of plot, you need to have the labels rotated  slightly. This can be done in the `theme()` layer

### Exercise 5: `[20 / 20 points]`

Feedback: [Not all code chunks were commented. Please do this so we know you're not just copying and pasting without going over what the code does.]

- [x] Resolved

### Overall: `[20 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by Jothish21** [comment]
Good Afternoon Sir,

--> Exercise 2-c : Made changes to plot, improved data-to-ink ratio and removed redundancy.
--> Exercise 3-c : Used grid.arrange() to arrange the plots in a grid
--> Exercise 4 : Changed the plot and made so that it shows price/bed over the years in different panels for all selected 8 neighborhoods which is easy to understand and interpret.
--> Exercise 5 : added comments for all code chunks

Thank you for evaluation :) and this feedback will be greatly helpful for learning from our mistakes.

**Comment by Gchism94** [comment]
Good job on the resubmission. You just need to watch out for axis-text readability (your exercise 4 boxplot). You now have 9.8/10 points for this assignment.

**Comment by Jothish21** [comment]
Hi Sir,

I have made changes to 4th question plot, rotated the x axis text to 45 degrees and adjusted horizontally to align, which should make the axis more readable. 
Thank you.

**Comment by Gchism94** [comment]
Looks good, you now received full credit.

**Comment by Jothish21** [comment]
Issue resolves:

--> Exercise 2-c : Made changes to plot, improved data-to-ink ratio and removed redundancy.
--> Exercise 3-c : Used grid.arrange() to arrange the plots in a grid
--> Exercise 4 : Changed the plot and made so that it shows price/bed over the years in different panels for all selected 8 neighborhoods which is easy to understand and interpret. rotated the x axis text to 45 degrees and adjusted horizontally to align, which should make the axis more readable.
--> Exercise 5 : added comments for all code chunks

Thank you for evaluation.
